export const enum Paths {
  SignUpScreen = 'sign-up-screen',
  SignInScreen = 'sign-in-screen',
  ForgotPasswordScreen = 'forgot-password-screen',
  NewPasswordScreen = 'new-password-screen',
  OTPVerificationScreen = 'otp-verification-screen',
  Home = 'home',
  Profile = 'profile',
  Booking = 'booking',
  Message = 'message',
  PersonalInfo = 'personalInfo',
  LanguageScreen = 'languageScreen',
  Notifications = 'notifications',
  HelpAndSupport = 'helpAndSupport',
  Security = 'security',
  UserCards = 'userCards',
  SignIn = 'SignIn',
  SignUp = 'SignUp',
  ForgotPassword = 'ForgotPassword',
  NewPassword = 'NewPassword',
  OTPVerification = 'OTPVerification',
  NavStack = 'NavStack',
}
